### ISSUE TITLE
HTTPS is not working

### ISSUE THREAD

**Issue by JaeDukSeo** [Nigh7Sh4de/buskit-server#12] opened 2019-02-02 02:39 UTC
HTTPS is not working

**Comment by Nigh7Sh4de** [comment] 2019-02-03 21:52
Duplicate of #11.

HTTPS is an implementation detail. In our case, we configured our nginx server to redirect HTTPS traffic to the koa server.

**Closed by Nigh7Sh4de** 2019-02-03 21:52 UTC
